"""Write results/KEY_NUMBERS.md: every number a drafter needs, by report section.

Generated from the result files, never typed. Each line names the file it came
from, so a reviewer can trace any number in the paper to disk.

Formatting follows APA 7: statistics that cannot exceed 1 (proportions,
precision, recall, correlations) drop the leading zero; RMSE and MAE, which can
exceed 1, keep it.
"""

import json

import pandas as pd

from . import config as C

R = C.RESULTS_DIR


def _j(name):
    return json.loads((R / name).read_text())


def b(x, d=3):
    """Bounded statistic: no leading zero (APA 7)."""
    s = f"{x:.{d}f}"
    return s.replace("0.", ".", 1) if s.startswith("0.") else s.replace("-0.", "-.", 1)


def u(x, d=4):
    """Unbounded statistic (RMSE, MAE): keep the leading zero."""
    return f"{x:.{d}f}"


def pct(x, d=1):
    return f"{x * 100:.{d}f}%"


def build(quick=False):
    L = []
    w = L.append
    if quick:
        w("# QUICK SMOKE TEST. SHRUNKEN GRIDS. DO NOT CITE ANY NUMBER IN THIS FILE.\n")
    w("# Key numbers for the Part 2 report\n")
    w("Generated by `python run_all.py`. Every number below is read from the file named in "
      "brackets. If a number in the paper does not appear here, it did not come from the pipeline.\n")

    d = _j("data_log.json")
    s, cl = d["shape"], d["cleaning"]
    w("## Setup: dataset and cleaning  [data_log.json]\n")
    w(f"- {s['n_ratings']:,} ratings from {s['n_users']:,} users on {s['n_items']:,} movies, "
      f"{s['first_rating_utc'][:10]} to {s['last_rating_utc'][:10]}.")
    w(f"- Density {b(s['density'], 4)} ({pct(s['density'])} of the user-movie matrix observed); "
      f"sparsity {pct(s['sparsity'])}.")
    w(f"- Mean rating {s['mean_rating']:.2f} (SD = {s['sd_rating']:.2f}).")
    w(f"- Cleaning: {cl['missing_values_ratings']} missing values, {cl['duplicate_user_item_pairs']} "
      f"duplicate user-movie pairs, {cl['ratings_outside_scale']} out-of-range ratings, "
      f"{cl['users_below_min_ratings']} users under {C.MIN_RATINGS_PER_USER} ratings. "
      f"Rows in {cl['rows_in']:,}, rows out {cl['rows_out']:,}.")
    w(f"- Data-quality notes: {cl['duplicate_titles']} titles appear under two movie ids "
      f"({cl['item_ids_with_duplicate_titles']} ids; kept separate, see README); "
      f"{cl['items_with_unknown_genre_flag']} movie(s) flagged genre 'unknown'; "
      f"{cl['non_numeric_zip_codes']} non-US zip codes.")
    w(f"- u.data SHA-256 `{d['ratings_sha256']}` ({d['fingerprint_status']}).\n")

    e = _j("eda_summary.json")["long_tail"]
    pv = _j("eda_summary.json")["popularity_vs_mean"]
    w("## Setup: exploratory analysis  [eda_summary.json, eda_*.csv]\n")
    w(f"- Ratings per user: median {e['users']['median']:.0f}, max {e['users']['max']}; "
      f"top 10% of users supply {pct(e['users']['share_of_ratings_from_top_10pct_users'])} of ratings; "
      f"Gini {b(e['users']['gini'])}.")
    w(f"- Ratings per movie: median {e['items']['median']:.0f}, max {e['items']['max']}; "
      f"top 10% of movies receive {pct(e['items']['share_of_ratings_on_top_10pct_items'])} of ratings, "
      f"top 20% receive {pct(e['items']['share_of_ratings_on_top_20pct_items'])}; "
      f"{e['items']['items_with_1_rating']} movies have exactly one rating, "
      f"{e['items']['items_with_under_10_ratings']} have fewer than 10; Gini {b(e['items']['gini'])}.")
    w(f"- SD of movie mean ratings: {pv['sd_of_item_means_under_10_ratings']:.2f} for movies with "
      f"<10 ratings vs {pv['sd_of_item_means_100_plus_ratings']:.2f} for 100+ ratings "
      f"(small-sample means are noisy; the case for regularized bias terms).")
    rd = pd.read_csv(R / "eda_rating_distribution.csv")
    w("- Rating distribution: " + ", ".join(f"{int(r.rating)} = {pct(r.share)}" for r in rd.itertuples()) + ".")
    dm = pd.read_csv(R / "eda_demographics.csv")
    g = dm[dm.attribute == "gender"].set_index("group")
    w(f"- Gender: {pct(g.loc['M', 'share_of_users'])} of users are male and supply "
      f"{pct(g.loc['M', 'share_of_ratings'])} of ratings.  [eda_demographics.csv]\n")

    w("## Setup: train/test split  [split_random.csv, temporal_comparison.csv]\n")
    tc = pd.read_csv(R / "temporal_comparison.csv")
    rr = tc[(tc.strategy == "random") & (tc.model == "svd_tuned")].iloc[0]
    w(f"- Random 80/20 split, seed {C.SEED}: {int(rr.n_train):,} training ratings, "
      f"{int(rr.n_test):,} test ratings. All tuning uses the training partition only.\n")

    w("## Model selection  [roster_comparison_random.csv]\n")
    ro = pd.read_csv(R / "roster_comparison_random.csv")
    w("| Model | Test RMSE | Test MAE | 5-fold CV RMSE (SD) |")
    w("|---|---|---|---|")
    for r in ro.itertuples():
        cv = (f"{u(r.cv_rmse_mean)} ({u(r.cv_rmse_sd)})" if pd.notna(getattr(r, "cv_rmse_mean", None))
              else "n/a")
        w(f"| {r.model} | {u(r.rmse)} | {u(r.mae)} | {cv} |")
    w("")
    w(f"Note: this table's CV column is {C.CV_FOLDS}-fold. The tuning searches below use "
      f"{C.TUNE_CV_FOLDS}-fold CV, as the assignment specifies, so each fold trains on less data "
      "and every score runs higher. Never compare a number from this table's CV column with a "
      "tuning CV number. Compare tuned against untuned only on the same folds (below) or on the "
      "held-out test set (Section 2).\n")

    w("## 1. Hyperparameter tuning  [tuning_*.json, tuning_surface_*.csv, tuning_sensitivity_*.csv]\n")
    labels = ["quick"] if quick else ["assignment", "expanded", "refined"]
    for lab in labels:
        t = _j(f"tuning_{lab}.json")
        w(f"- {lab} grid: {t['n_candidates']} candidates x {t['cv_folds']} folds on the training "
          f"partition. Best CV RMSE {u(t['best_cv_rmse'])} (fold SD {u(t['best_cv_rmse_sd_across_folds'])}) "
          f"at {t['best_params']}; worst {u(t['worst_cv_rmse'])}; spread {u(t['cv_rmse_spread'])}. "
          f"Search took {t['search_seconds']:.0f} s.")
        if t.get("default_config_cv_rmse") is not None:
            w(f"  - Untuned SVD defaults on the same folds: CV RMSE {u(t['default_config_cv_rmse'])}, "
              f"so this grid's best improves on them by {u(t['default_config_cv_rmse'] - t['best_cv_rmse'])}.")
        if t.get("top10_cv_rmse_spread") is not None and t["n_candidates"] >= 10:
            w(f"  - The 10 best candidates lie within {u(t['top10_cv_rmse_spread'])} CV RMSE of each other.")
        edge = t.get("best_on_grid_edge") or {}
        w(f"  - Winner on the edge of the grid: " + (", ".join(f"{k} ({v})" for k, v in edge.items())
          if edge else "none; the optimum is interior on every axis") + ".")
        sens = pd.read_csv(R / f"tuning_sensitivity_{lab}.csv")
        rng = sens.groupby("parameter").mean_cv_rmse.agg(lambda x: x.max() - x.min()).sort_values(ascending=False)
        w(f"  - Sensitivity (range of mean CV RMSE across each parameter's values): "
          + "; ".join(f"{k} {u(v)}" for k, v in rng.items()) + ".")
    sel = _j("tuning_selected.json")
    w(f"- Selected: {sel['grid']} grid, {sel['params']}, CV RMSE {u(sel['cv_rmse'])}.")
    if sel.get("best_on_grid_edge"):
        w("- **The selected configuration still sits on a grid edge "
          f"({', '.join(f'{k} {v}' for k, v in sel['best_on_grid_edge'].items())}).** Say so in "
          "Section 1. Check the refined surface: if the top few candidates differ by less than the fold "
          "SD, the edge is a flat region and further search would not change the conclusion.")
    w("")

    f = _j("final_evaluation.json")
    im = f["improvement_over_default"]
    w("## 2. Final model evaluation  [final_evaluation.json, final_*.csv]\n")
    w(f"- Tuned SVD, held-out test: RMSE {u(f['test']['rmse'])}, MAE {u(f['test']['mae'])}. "
      f"Training RMSE {u(f['test']['train_rmse'])} (gap {u(f['test']['train_test_rmse_gap'])}).")
    w(f"- Default SVD: RMSE {u(im['default_svd_test_rmse'])}, MAE {u(im['default_svd_test_mae'])}. "
      f"Tuning reduced test RMSE by {u(im['rmse_reduction'])} ({pct(im['rmse_reduction_pct'], 2)}) "
      f"and MAE by {u(im['mae_reduction'])}.")
    w(f"- Is that reduction larger than the default model's fold-to-fold SD "
      f"({u(im['default_svd_cv_rmse_sd'])})? **{'Yes' if im['reduction_exceeds_default_cv_sd'] else 'No: report it as within noise'}**.")
    w(f"- Tuned SVD vs bias-only baseline: {u(im['tuned_vs_baseline_only_rmse_reduction'])} lower RMSE "
      f"(baseline {u(im['baseline_only_test_rmse'])}). This is what the latent factors add.")
    c = f["compression"]
    w(f"- Compression toward the mean: SD of predictions {c['sd_predicted']:.2f} vs SD of true ratings "
      f"{c['sd_actual']:.2f}; true 1s predicted at {c['mean_predicted_when_true_is_1']:.2f} on average, "
      f"true 5s at {c['mean_predicted_when_true_is_5']:.2f}.  [final_error_by_true_rating.csv]")
    for key, who in (("user_train_ratings", "users"), ("item_train_ratings", "movies")):
        bins = f["rmse_by_support"][key]
        w(f"- RMSE by {who}' training volume, lightest to heaviest quintile: "
          + ", ".join(f"{x['label']}: {u(x['rmse'], 3)}" for x in bins) + ".")
    w(f"- Ranking (test items only, k = {C.TOP_K}, relevant = true rating >= {C.RELEVANCE_THRESHOLD:g}):")
    for m, r in f["ranking"].items():
        w(f"  - {m}: precision@{r['k']} {b(r['precision_at_k'])}, recall@{r['k']} {b(r['recall_at_k'])}")
    rk = f["ranking"]
    if rk["svd_tuned"]["precision_at_k"] < rk["svd"]["precision_at_k"]:
        w(f"- **The RMSE-tuned model ranks worse than the untuned one** (precision@{C.TOP_K} "
          f"{b(rk['svd_tuned']['precision_at_k'])} vs {b(rk['svd']['precision_at_k'])}). Lower RMSE did not "
          "produce better recommendation lists. See Section 3, thin-evidence recommendations, for why.")
    w(f"- Largest misses include: {', '.join(map(str, f['largest_error_titles']))}.  [final_largest_errors.csv]")

    ts = _j("temporal_summary.json")
    w("\n### Evaluation validity: random vs chronological splits  [temporal_summary.json]\n")
    for k, v in ts["svd_tuned_rmse_by_split"].items():
        w(f"- {k}: tuned SVD RMSE {u(v)}; share of test ratings whose movie has training "
          f"ratings from later in time {b(ts['future_information_by_split'][k])}.")
    w(f"- Random to global chronological: RMSE +{u(ts['rmse_increase_random_to_global'])} "
      f"({pct(ts['rmse_increase_random_to_global_pct'])}).")
    w(f"- Global chronological: {pct(ts['global_chrono_cold_user_share_of_test'])} of test ratings come "
      f"from users unseen in training; RMSE {u(ts['global_chrono_warm_user_rmse'])} for returning users vs "
      f"{u(ts['global_chrono_cold_user_rmse'])} for new users.")
    w("- SVD minus bias-only RMSE by split (negative = SVD better): "
      + "; ".join(f"{k} {v:+.4f}" for k, v in ts["svd_minus_baseline_rmse_by_split"].items()) + ".\n")

    fa = _j("fairness_summary.json")
    gr = fa["groups"]
    ge = pd.read_csv(R / "fairness_group_errors.csv")
    w("## 3. Ethical considerations  [fairness_summary.json, fairness_*.csv]\n")
    w(f"- Overall test RMSE {u(gr['overall_rmse'])}. User-resampled bootstrap, {C.BOOTSTRAP_REPS} reps.")
    for attr in ("gender", "age_band"):
        t = ge[ge.attribute == attr]
        w(f"- By {attr}: " + "; ".join(
            f"{r.group} {u(r.rmse, 3)} [{u(r.rmse_ci_low, 3)}, {u(r.rmse_ci_high, 3)}], "
            f"n = {r.n_users} users, {r.mean_train_ratings_per_user:.0f} train ratings/user"
            for r in t.itertuples()) + ".")
    gg = gr["gender_gap"]
    if gg:
        w(f"- Gender gap (F minus M): {gg['rmse_F_minus_M']:+.4f}, 95% CI [{gg['ci_low']:+.4f}, "
          f"{gg['ci_high']:+.4f}]; CI {'excludes' if gg['ci_excludes_zero'] else 'includes'} zero.")
    w(f"- Spearman correlation between a user's training volume and their RMSE: "
      f"{b(gr['spearman_user_train_ratings_vs_user_rmse'])} (the activity confound).")
    if gr.get("gender_gap_by_activity_quartile"):
        w("- Gender gap (F minus M RMSE) within users' activity quartiles: "
          + "; ".join(f"{k} {v:+.3f}" for k, v in gr["gender_gap_by_activity_quartile"].items())
          + f". Positive in every quartile: **{'yes' if gr['gender_gap_positive_in_every_quartile'] else 'no'}**. "
          "If yes, the gap is not explained by women rating fewer movies. "
          "Check n_users per cell in fairness_gender_by_activity.csv; the heaviest quartile has few women.")
    occ = ge[ge.attribute == "occupation"].sort_values("rmse")
    w(f"- Occupation extremes: lowest {occ.iloc[0].group} {u(occ.iloc[0].rmse, 3)} "
      f"(n = {occ.iloc[0].n_users}), highest {occ.iloc[-1].group} {u(occ.iloc[-1].rmse, 3)} "
      f"(n = {occ.iloc[-1].n_users}). Small groups have wide intervals; check before claiming a gap.")
    p = fa["popularity"]
    w(f"- Exposure by popularity: the most-rated 10% of movies receive {pct(p['share_of_train_ratings_on_top_decile'])} "
      f"of training ratings and {pct(p['share_of_recs_from_top_decile'])} of top-10 recommendations. "
      f"The least-rated half of the catalog receives {pct(p['share_of_recs_from_bottom_half'])} of recommendations.")
    mr = pd.read_csv(R / "fairness_most_recommended.csv")
    if "title" in mr:
        w("- Most-recommended movies (share of users whose top 10 includes it; training ratings; training mean): "
          + "; ".join(f"{r.title} {pct(r.share_of_users, 0)}, n = {int(r.train_ratings)}, mean {r.train_mean_rating:.2f}"
                      for r in mr.head(4).itertuples()) + ".  [fairness_most_recommended.csv]")
    w(f"- Thin-evidence recommendations: {pct(p['share_of_recs_to_items_under_10_train_ratings'])} of all "
      f"recommendations go to movies with fewer than 10 training ratings "
      f"({pct(p['share_of_catalog_under_10_train_ratings'])} of the catalog); "
      f"{p['items_under_10_train_ratings_in_over_half_of_lists']} such movie(s) appear in over half of all lists.")
    if "mean_pairwise_list_overlap" in p:
        w(f"- Personalization: two random users' top-10 lists overlap by {b(p['mean_pairwise_list_overlap'])} "
          "on average (Jaccard; 0 = entirely different lists, 1 = identical).")
    w(f"- Catalog coverage of all top-10 lists: {pct(p['catalog_coverage'])} "
      f"({p['distinct_items_recommended']} of {s['n_items']:,} movies); Gini of recommendation counts "
      f"{b(p['gini_of_recommendation_counts'])}; the single most-recommended movie appears in "
      f"{pct(p['most_recommended_item_share_of_users'])} of users' lists.\n")

    mt = pd.read_csv(R / "mitigation_min_support.csv")
    w("### Mitigation: minimum-support threshold  [mitigation_min_support.csv, mitigation_min_support.png]\n")
    w(f"Movies with fewer than N training ratings are excluded from recommendation lists. Recall is "
      f"charged for relevant movies the filter makes unrecommendable. Thin = fewer than {C.THIN_EVIDENCE} "
      "training ratings.\n")
    w(f"| Model | Min. ratings | Precision@{C.TOP_K} | Recall@{C.TOP_K} | Recs to thin movies | "
      "List overlap | Distinct movies recommended | Top movie's share of lists |")
    w("|---|---|---|---|---|---|---|---|")
    for r in mt.itertuples():
        w(f"| {r.model} | {'none' if r.min_support == 0 else r.min_support} | {b(r.precision_at_k)} | "
          f"{b(r.recall_at_k)} | {pct(r.share_of_recs_to_thin_items)} | {b(r.mean_pairwise_list_overlap)} | "
          f"{r.distinct_items_recommended} | {pct(r.most_recommended_item_share_of_users)} |")
    w("\nChoose N on the tradeoff and say why. Do not choose it by which row has the best test precision, "
      "which would tune on the test set.\n")

    ex = pd.read_csv(R / "final_example_recommendations.csv")
    w("## 4. Real-world application  [final_example_recommendations.csv, final_top10_all_users.csv]\n")
    for kind, g in ex.groupby("user_type", sort=False):
        w(f"- {kind} user ({int(g.user_id.iloc[0])}, {int(g.train_ratings.iloc[0])} training ratings): "
          + "; ".join(g.sort_values("rank").title.head(5).astype(str)) + ".")
    ro_fit = ro.set_index("model")
    w(f"- Fit time on {int(rr.n_train):,} ratings: default SVD {ro_fit.loc['svd', 'fit_seconds']:.1f} s; "
      f"top-10 lists for all users scored in one matrix product.")

    (R / "KEY_NUMBERS.md").write_text("\n".join(L) + "\n")
    return R / "KEY_NUMBERS.md"
